Remove backend_ignore_ci job (#7854)
## Describe your changes
Github branch protections just require that a job with a given name has
a passed status.

As a monorepo, we don't want to run all tests (frontend/mobile/backend)
on all PRs - only the relevant tests.

In the past, we had a standard of creating an "ignore" job that would
create passed jobs with the names that Github branch protections were
looking for _if files were changed outside of the desired directory._

This had the unintended side effect of causeing both the frontend and
backend "ignore" jobs to be run when a PR had changes in both the
backend and the frontend folders, essentially not requiring any status
checks to merge a PR like that

This changes to the more standard practice of just skipping a job (which
reports to Github branch protections as a "pass") if no relevant files
are changed

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse
output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->

diff --git a/.github/workflows/backend_ci.yml b/.github/workflows/backend_ci.yml
--- a/.github/workflows/backend_ci.yml
+++ b/.github/workflows/backend_ci.yml
@@ -2,15 +2,9 @@ name: Backend CI
 
 on:
   push:
-    paths:
-      - 'backend/**'
-
     branches:
       - master
-
   pull_request:
-    paths:
-      - 'backend/**'
 
 env:
   CARGO_TERM_COLOR: always
@@ -19,10 +13,24 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-ci-check-test
   cancel-in-progress: true
 
-# The names of these jobs are important since they're used in Github branch protections
-
 jobs:
+  files-changed:
+    name: Determine if relevant files changed
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
+        id: changes
+        with:
+          filters: | 
+            src:
+              - 'backend/**'
+    outputs:
+      filesChanged: ${{ steps.changes.outputs.src }}
+
   check_test:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     runs-on: 16core
     environment: dev
     services:
@@ -83,7 +91,9 @@ jobs:
         env:
           DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
 
-  integration_migration_tests:
+  integration_tests:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     runs-on: 16core
     environment: dev
     strategy:
@@ -108,7 +118,6 @@ jobs:
       EXPECTED_SERVER_VERSION: ${{ github.sha }}
       IT_PHONE_NUMBERS: '["+1 202 952 1443", "+1 202 831 8398", "+1 202 946 3154", "+1 202 937 0987", "+1 202 759 2344", "+1 202 946 1521", "+1 202 998 5931", "+1 202 952 9077", "+1 202 740 9135", "+1 202 519 1954"]'
       ENVIRONMENT: ci
-    if: success()
     steps:
       - uses: actions/checkout@v3
 
@@ -208,6 +217,8 @@ jobs:
           fi
 
   clippy:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     runs-on: 16core
 
     steps:
@@ -228,3 +239,17 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           args: --manifest-path ./backend/Cargo.toml -- -D warnings
           toolchain: 1.74.0
+
+  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
+  # Add all jobs in this workflow to this job's `needs`
+  backend-ci:
+    runs-on: ubuntu-latest
+    needs: [check_test, integration_tests, clippy]
+    if: always()
+    steps:
+      - name: Success
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Fail
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
