Skip building image if it has already been built for the commit (#9978)
## Describe your changes
<!--- An in-depth description of the changes made by this PR. Technical
details and possible side effects. -->
This allows for re-running CI jobs even if it already succeeded.
Otherwise, the job would fail on the push on the second run. CI
definition is bound by the commit, so a second build should be the same
as the first, except for external non-determinism. Note that this is
similar to the behavior we had before where we avoided rebuilding images
if already exist, so that caveat is not new.

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse
output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->

diff --git a/.github/workflows/backend_ci.yml b/.github/workflows/backend_ci.yml
--- a/.github/workflows/backend_ci.yml
+++ b/.github/workflows/backend_ci.yml
@@ -84,11 +84,16 @@ jobs:
         run: |
           set -euxo pipefail
 
+          # The image may already exist in the registry if we are retrying the
+          # job after it already succeeded. Exit early in this case.
+          IMG_REF=${REGISTRY}/${REPO}:${TAG}
+          docker manifest inspect "${IMG_REF}" && echo "Image ${IMG_REF} has already been built. Skipping." && exit 0 || echo "Building ${IMG_REF}..."
+
           echo '${{toJSON(matrix.args) }}' | jq -r '. | to_entries | map("--build-arg \(.key)=\(.value | @sh)") | join(" ")' | \
             xargs docker buildx build \
               --platform linux/amd64 \
               --file ./images/${{ matrix.dockerfile }}/Dockerfile \
-              --tag $REGISTRY/$REPO:$TAG \
+              --tag ${IMG_REF} \
               --push \
               ${{ github.ref == 'refs/heads/master' && '--cache-to type=registry,ref=${REGISTRY}/build-cache:${REPO}-master,compression=zstd,mode=max,image-manifest=true,oci-mediatypes=true' || '' }} \
               --cache-from type=registry,ref=${REGISTRY}/build-cache:${REPO}-master \
