Revert "Run  `Check valid db migrations`  before integration tests" (#4262)
Reverts onefootprint/monorepo#4239

diff --git a/.github/workflows/backend_ci.yml b/.github/workflows/backend_ci.yml
--- a/.github/workflows/backend_ci.yml
+++ b/.github/workflows/backend_ci.yml
@@ -138,34 +138,6 @@ jobs:
           workspaces: |
             backend
 
-      - name: Install diesel cli
-        run: cargo install diesel_cli --version 1.4.1 --no-default-features --features postgres
-
-      - name: Check valid db migrations
-        working-directory: ./backend/components/db/schema
-        run: |
-          NUM_FILES=`ls migrations | wc -l`
-          NUM_TO_REVERT=$(( $NUM_FILES < 1 ? $NUM_FILES : 1 ))
-          echo "Reverting $NUM_TO_REVERT migrations"
-
-          for ((i=0; i<$NUM_TO_REVERT; i++))
-          do
-            echo $i
-            diesel migration revert
-            if [ $? -ne 0 ]; then
-              echo "failed to properly revert"
-              exit 1
-            fi
-          done
-
-          echo "Reverted $NUM_TO_REVERT migrations, running again"
-
-          diesel migration run
-          if [ $? -ne 0 ]; then
-            echo "failed to properly restore"
-            exit 1
-          fi
-
       - name: Setup Python # Set Python version
         uses: actions/setup-python@v3
         with:
@@ -246,6 +218,34 @@ jobs:
           body: |
             ${{ steps.test_results.outputs.body }}
           edit-mode: replace
+
+      - name: Install diesel cli
+        run: cargo install diesel_cli --version 1.4.1 --no-default-features --features postgres
+
+      - name: Check valid db migrations
+        working-directory: ./backend/components/db/schema
+        run: |
+          NUM_FILES=`ls migrations | wc -l`
+          NUM_TO_REVERT=$(( $NUM_FILES < 1 ? $NUM_FILES : 1 ))
+          echo "Reverting $NUM_TO_REVERT migrations"
+
+          for ((i=0; i<$NUM_TO_REVERT; i++))
+          do
+            echo $i
+            diesel migration revert
+            if [ $? -ne 0 ]; then
+              echo "failed to properly revert"
+              exit 1
+            fi
+          done
+
+          echo "Reverted $NUM_TO_REVERT migrations, running again"
+
+          diesel migration run
+          if [ $? -ne 0 ]; then
+            echo "failed to properly restore"
+            exit 1
+          fi
 
   clippy:
     runs-on: beast
