fix enclave deploy (#9529)
## Describe your changes
<!--- An in-depth description of the changes made by this PR. Technical
details and possible side effects. -->

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse
output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->

diff --git a/.github/workflows/backend_build.yml b/.github/workflows/backend_build.yml
--- a/.github/workflows/backend_build.yml
+++ b/.github/workflows/backend_build.yml
@@ -166,7 +166,7 @@ jobs:
         run: |
           account="$(aws sts get-caller-identity --query "Account" --output text)"
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
-          docker pull ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${{ needs.extract_commit.outputs.enclaveComponentVersion }} && docker tag ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${{ needs.extract_commit.outputs.enclaveComponentVersion }} enclave_pkg:${{ needs.extract_commit.outputs.enclaveComponentVersion }} || echo "Image not found"
+          docker pull ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${{ needs.extract_commit.outputs.enclaveComponentVersion }} && docker tag ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${{ needs.extract_commit.outputs.enclaveComponentVersion }} enclave:${{ needs.extract_commit.outputs.enclaveComponentVersion }} || echo "Image not found"
 
       - uses: actions/checkout@v3
         with:
@@ -184,10 +184,10 @@ jobs:
           echo "create image tagged as ${componentVersion}"
 
           # check cache or build
-          docker inspect enclave_pkg:${componentVersion} && echo "Fetched from package cache"|| (echo "Cache miss, building..." && make build-enclave-docker && docker tag enclave:latest enclave_pkg:${componentVersion})
+          docker inspect enclave:${componentVersion} && echo "Fetched from package cache"|| (echo "Cache miss, building..." && make build-enclave-docker && docker tag enclave:latest enclave:${componentVersion})
 
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
-          docker tag enclave_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${componentVersion}
-          docker tag enclave_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:latest
-          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${componentVersion}
-          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:latest
+          docker tag enclave:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${componentVersion}
+          docker tag enclave:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:latest
+          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${componentVersion}
+          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:latest
