[BE-16] Update e2e job to allow it to block merging PRs (#9712)
## Describe your changes
In order for a job to be used for branch protections, we need the job to
always run. This follows the model we have in other jobs where we run a
no-op job when there aren't changes in relevant files

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse
output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->

diff --git a/.github/workflows/frontend_e2e.yml b/.github/workflows/frontend_e2e.yml
--- a/.github/workflows/frontend_e2e.yml
+++ b/.github/workflows/frontend_e2e.yml
@@ -1,17 +1,14 @@
-name: E2E
+name: Frontend E2E
 
 on:
+  push:
+    branches:
+      - master
   pull_request:
-    paths:
-      - '.github/workflows/frontend_e2e.yml'
-      - 'frontend/apps/auth/**'
-      - 'frontend/apps/components/**'
-      - 'frontend/apps/handoff/**'
-      - 'frontend/packages/**'
-
+  
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
 
 env:
   E2E_UPDATE_UTOKEN: ''
@@ -19,7 +16,27 @@ env:
   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
 
 jobs:
+  files-changed:
+    name: Determine if relevant files changed
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
+        id: changes
+        with:
+          filters: |
+            src:
+              - '.github/workflows/frontend_e2e.yml'
+              - 'frontend/apps/auth/**'
+              - 'frontend/apps/components/**'
+              - 'frontend/apps/handoff/**'
+              - 'frontend/packages/**'
+    outputs:
+      filesChanged: ${{ steps.changes.outputs.src }}
+
   test:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     runs-on: frontend_runner
     steps:
       - name: Get update auth methods token
@@ -87,3 +104,17 @@ jobs:
                 body: "E2E HTML report: [report](https://pwe2e.z13.web.core.windows.net/${{ steps.upload-report.outputs.report-dir }}/index.html)"
               })
             }
+
+  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
+  # Add all jobs in this workflow to the `needs` here
+  frontend-e2e:
+    runs-on: ubuntu-latest
+    needs: [test]
+    if: always()
+    steps:
+      - name: Success
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Fail
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
