Replace ignore CI jobs for frontend/mobile (#7857)
## Describe your changes
Doing the same we did to the backend job in #7854 to these frontend
jobs. Much more context in that PR

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse
output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->

diff --git a/.github/workflows/frontend_ci.yml b/.github/workflows/frontend_ci.yml
--- a/.github/workflows/frontend_ci.yml
+++ b/.github/workflows/frontend_ci.yml
@@ -4,12 +4,7 @@ on:
   push:
     branches:
       - master
-    paths:
-      - 'frontend/**'
   pull_request:
-    paths:
-      - 'frontend/**'
-      - '.github/workflows/frontend_ci.yml'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -22,7 +17,23 @@ env:
 # The names of these jobs are important since they're used in Github branch protections
 
 jobs:
+  files-changed:
+    name: Determine if relevant files changed
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
+        id: changes
+        with:
+          filters: | 
+            src:
+              - 'frontend/**'
+    outputs:
+      filesChanged: ${{ steps.changes.outputs.src }}
+
   install-dependencies:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     strategy:
       matrix:
         node-version: [18.x]
@@ -47,11 +58,11 @@ jobs:
         run: yarn install --frozen-lockfile
 
   lint:
+    needs: install-dependencies
     strategy:
       matrix:
         node-version: [18.x]
     runs-on: frontend_runner
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
 
@@ -71,11 +82,11 @@ jobs:
         run: yarn lint:ci
 
   format:
+    needs: install-dependencies
     strategy:
       matrix:
         node-version: [18.x]
     runs-on: frontend_runner
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
@@ -94,11 +105,11 @@ jobs:
         run: yarn format
 
   test:
+    needs: install-dependencies
     strategy:
       matrix:
         node-version: [18.x]
     runs-on: frontend_runner
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
@@ -117,11 +128,11 @@ jobs:
         run: yarn test:ci
 
   typecheck:
+    needs: install-dependencies
     strategy:
       matrix:
         node-version: [18.x]
     runs-on: frontend_runner
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
@@ -140,6 +151,8 @@ jobs:
         run: yarn typecheck
 
   audit:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     strategy:
       matrix:
         node-version: [18.x]
@@ -153,3 +166,17 @@ jobs:
       - name: Audit for vulnerabilities
         working-directory: ./frontend
         run: npx audit-ci@^6 --config ./audit-ci.jsonc
+
+  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
+  # Add all jobs in this workflow to the `needs` here
+  frontend-ci:
+    runs-on: ubuntu-latest
+    needs: [files-changed, install-dependencies, lint, format, test, typecheck, audit]
+    if: always()
+    steps:
+      - name: Success
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Fail
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
diff --git a/.github/workflows/mobile_ci.yml b/.github/workflows/mobile_ci.yml
--- a/.github/workflows/mobile_ci.yml
+++ b/.github/workflows/mobile_ci.yml
@@ -4,12 +4,7 @@ on:
   push:
     branches:
       - master
-    paths:
-      - 'mobile/**'
   pull_request:
-    paths:
-      - 'mobile/**'
-      - '.github/workflows/mobile_ci.yml'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -20,10 +15,24 @@ env:
   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
   API_BASE_URL: https://api.dev.onefootprint.com
 
-# The names of these jobs are important since they're used in Github branch protections
-
 jobs:
+  files-changed:
+    name: Determine if relevant files changed
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
+        id: changes
+        with:
+          filters: | 
+            src:
+              - 'mobile/**'
+    outputs:
+      filesChanged: ${{ steps.changes.outputs.src }}
+
   install-dependencies:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -49,13 +58,13 @@ jobs:
         if: steps.cache-dependencies.outputs.cache-hit != 'true'
         run: yarn install --frozen-lockfile
 
-  lint-mobile:
+  lint:
+    needs: install-dependencies
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         node-version: [18.x]
         os: [ubuntu-latest]
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
 
@@ -76,13 +85,13 @@ jobs:
         working-directory: ./mobile
         run: yarn lint:ci
 
-  format-mobile:
+  format:
+    needs: install-dependencies
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         node-version: [18.x]
         os: [ubuntu-latest]
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
@@ -101,13 +110,13 @@ jobs:
         working-directory: ./mobile
         run: yarn format:ci
 
-  test-mobile:
+  test:
+    needs: install-dependencies
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         node-version: [18.x]
         os: [ubuntu-latest]
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
@@ -126,13 +135,13 @@ jobs:
         working-directory: ./mobile
         run: yarn test:ci
 
-  typecheck-mobile:
+  typecheck:
+    needs: install-dependencies
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         node-version: [18.x]
         os: [ubuntu-latest]
-    needs: install-dependencies
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
@@ -151,7 +160,9 @@ jobs:
         working-directory: ./mobile
         run: yarn typecheck
 
-  audit-mobile:
+  audit:
+    needs: [files-changed]
+    if: needs.files-changed.outputs.filesChanged == 'true'
     strategy:
       matrix:
         node-version: [18.x]
@@ -165,3 +176,17 @@ jobs:
       - name: Audit for vulnerabilities
         working-directory: ./mobile
         run: npx audit-ci@^6 --config ./audit-ci.jsonc
+
+  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
+  # Add all jobs in this workflow to the `needs` here
+  mobile-ci:
+    runs-on: ubuntu-latest
+    needs: [files-changed, install-dependencies, lint, format, test, typecheck, audit]
+    if: always()
+    steps:
+      - name: Success
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Fail
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
