[FP-268] add valid db migrations check (#170)

diff --git a/.github/workflows/rust_ci.yml b/.github/workflows/rust_ci.yml
--- a/.github/workflows/rust_ci.yml
+++ b/.github/workflows/rust_ci.yml
@@ -58,7 +58,7 @@ jobs:
           DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
 
   integration_tests:
-    name: run local integration tests
+    name: run local integration tests + check valid db migrations
     runs-on: ubuntu-latest
     environment: dev
     strategy:
@@ -162,3 +162,31 @@ jobs:
           path: ci/report.html
         # Use always() to always run this step to publish test results when there are test failures
         if: ${{ always() }}
+      
+      - name: Install diesel cli
+        run: cargo install diesel_cli --no-default-features --features postgres
+
+      - name: Check valid db migrations
+        working-directory: components/db
+        run: |
+          NUM_FILES=`ls migrations | wc -l`
+          NUM_TO_REVERT="$(($NUM_FILES - 1))"
+          echo "Reverting $NUM_TO_REVERT migrations"
+
+          for ((i=0; i<=$NUM_TO_REVERT; i++))
+          do
+            echo $i
+            diesel migration revert
+            if [ $? -ne 0 ]; then
+              echo "failed to properly revert"
+              exit 1
+            fi
+          done
+
+          echo "Reverted $NUM_TO_REVERT migrations, running again"
+
+          diesel migration run
+          if [ $? -ne 0 ]; then
+            echo "failed to properly restore"
+            exit 1
+          fi
